// This file is auto-generated by the `update-kc-gen` command. Do not edit it manually.
// Hash: 36e0ee2a6a3e51ec9e40a8d21a534adfa58eba3505014882dad8a9a0789e96f3

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

import { lazy, type ReactNode, Suspense } from 'react'

export type ThemeName = 'aisflow'

export const themeNames: ThemeName[] = ['aisflow']

export type KcEnvName = never

export const kcEnvNames: KcEnvName[] = []

export const kcEnvDefaults: Record<KcEnvName, string> = {}

/**
 * NOTE: Do not import this type except maybe in your entrypoint.
 * If you need to import the KcContext import it either from src/login/KcContext.ts or src/account/KcContext.ts.
 * Depending on the theme type you are working on.
 */
export type KcContext = import('./login/KcContext').KcContext

declare global {
	interface Window {
		kcContext?: KcContext
	}
}

export const KcLoginPage = lazy(() => import('./login/KcPage'))

export function KcPage(props: { kcContext: KcContext; fallback?: ReactNode }) {
	const { kcContext, fallback } = props
	return (
		<Suspense fallback={fallback}>
			{(() => {
				switch (kcContext.themeType) {
					case 'login':
						return <KcLoginPage kcContext={kcContext} />
				}
			})()}
		</Suspense>
	)
}

// NOTE: This is exported here only because in Webpack environnement it works differently
export const BASE_URL = import.meta.env.BASE_URL

// NOTE: This is only exported here because you're supposed to import type from different packages
// Depending of if you are using Vite, Webpack, ect...
export type { Meta, StoryObj } from '@storybook/react-vite'
